# File: .github/workflows/repo-sync.yml

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1.1.2
      env:
        SOURCE_REPO: "https://aaabddcbc4ee4cfac71a617fa2e5e81599ba2bd3@github.com/saikatsaha9896/Sample.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "https://aaabddcbc4ee4cfac71a617fa2e5e81599ba2bd3@github.com/saikatsaha9896/git-sync.git"
        DESTINATION_BRANCH: "develop"
        #SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
